export default {
    GET_ALL_CONTACTS: "GET_ALL_CONTACTS",
    CREATE_CONTACT: "CREATE_CONTACT",
    UPDATE_CONTACT: "UPDATE_CONTACT",
    GET_CONTACT: "GET_CONTACT",
    DELETE_CONTACT: "DELETE_CONTACT",
}