name: docker image ci

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: login on docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: build the docker image
      run: docker build . --file dockerfile --tag wastingnotime/contacts-frontend-mithril-flux

    - name: push the docker image
      run: docker push wastingnotime/contacts-frontend-mithril-flux
